### ISSUE TITLE
Reverse linkedlist using iteration method

### ISSUE THREAD

**Issue by KENILSHAHH** [TechMangalam/DSA-OpenSource#58]
i have a an easy O(n) solution of reversing a linkedlist using iteration method. I would like to contribute towards the same

**Comment by KENILSHAHH** [comment]
Please assign me for this issue. I have an O(n) and constant space solution for the above problem

**Comment by KENILSHAHH** [comment]
Hey @TechMangalam, hope you are doing well. I have added a pull request for the iterative algorithm of reversed linkedlist file with iterative approach. please review and merge the same

**Comment by TechMangalam** [comment]
pull request merged
